packages_list = """
    "@daily-co/daily-js": "^0.9.994",
    "@reduxjs/toolkit": "^1.4.0",
    "@sentry/browser": "^5.27.2",
    "@tailwindcss/ui": "^0.6.2",
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@uppy/robodog": "^1.9.8",
    "agora-rtc-sdk-ng": "^4.1.1",
    "axios": "^0.21.0",
    "bowser": "^2.11.0",
    "boxicons": "^2.0.7",
    "color": "^3.1.3",
    "css-element-queries": "^1.2.3",
    "date-fns": "^2.16.1",
    "debug": "~4.1.1",
    "emoji-mart": "^3.0.0",
    "lodash": "^4.17.20",
    "nanoid": "^3.1.16",
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "query-string": "^6.13.6",
    "react": "^16.13.1",
    "react-beautiful-dnd": "^13.0.0",
    "react-datepicker": "^3.3.0",
    "react-dom": "^16.13.1",
    "react-dom-confetti": "^0.2.0",
    "react-draggable": "^4.4.3",
    "react-easy-crop": "^3.2.2",
    "react-google-login": "^5.1.22",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^6.9.6",
    "react-input-slider": "^6.0.0",
    "react-lazyload": "^3.1.0",
    "react-linkify": "^1.0.0-alpha",
    "react-masonry-css": "^1.0.14",
    "react-modal": "^3.11.2",
    "react-phone-number-input": "^3.1.8",
    "react-portal-tooltip": "^2.4.7",
    "react-redux": "^7.2.2",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-select": "^3.1.0",
    "react-share": "^4.3.1",
    "react-switch": "^5.0.1",
    "react-table": "^7.6.1",
    "react-toastify": "^6.0.9",
    "react-tooltip": "^4.2.10",
    "recharts": "^1.8.5",
    "video.js": "^7.10.2"
"""
packages = []
for line in packages_list.split("\n"):
  parts = line.split("\"")
  if len(parts) > 1:
    packages.append(parts[1])
print("yarn " + " ".join(packages))